---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-secret
  namespace: default
spec:
  encryptedData:
    password: AgCjIjuTJ3kSbVK2oNZHyrEGpOMydpyfUuneaSYGL2WuRvJjeiX2C3bxKziDwBLLlFbo6+V2YJHvNK0WxMMtcFe+BtdNsBa1GF5iZS8vNeIyWEMnpJ8tjkQlvrB769e8sPh+7Ng+Ckf8SRnsmDxE8J9bI1UoSaGCYIUNNSz/kGn/LWmVK1AzYX7ZtIYNRL2QNAlhmzP178wWcXVn8nRzquR+KLLzBf0SlZbaBC9UodxRrjoFzPEL+hZ9jmROcLeIMRmIQN8XozwVli+KgDVplOllkftbJUXCUZppqEpzMJWUpr2FF3hT/FZXglYCF6Vlgy379arcnkam3hghnMuyLEIXt5rAMV9H+b5cDs0bbvf+JtQJLa6x2l/qy9YnZq3R843Xvcam1x+O1DfXNifqqG9uxpj9z76cAa4ILCod+ySW+BLuPQ9QiXwSQYP6YW5g91gH9vHQyEWaxfYfNeI1PXlTJDlnk3pbFiq9uHIc/iSgLHjpeKGha9LvUYUG7mzGSDTIC2CcVn9Srbzbj+awO0ZLsijm82jJ7lLzGq7uH1pppLVulf8BqaXtvD6IS2oTL2WbGtkHtKwvPfFOu720oftnw0tUGJcqU5eHQ83xVx+sEc+evftL8b4us9yBUI7gyc91xkkMdLMW0pXTwyf3WiwJvkfDmWpo9wxY1fx8vcfYeXj5SIkorZ/VXXCvPRWHp/+FNF6GqJZtb5KywSs0Hg==
    username: AgA6PaKGIGLtIPcSaoGKOb3elf0/3zwJVTDYLsOtH0ozcolCZyHeZz0vCEGZSuI31dPB1l/DQdGhaK9foVzuOKqYYh3lWpR+ZuGp9G+P8WaTNlkrv/wBBwaN38BKv3YrQnZ2yTXiXz6nwIAEQnFU11ohV9VJr3816DkzSmyRYnE7yx77Cue/JQ9jzkqORu1waqIp2fdNXpLOwt1HKrpzhU34sSD7upGw4UWzCyF1F+TnnOB1FbBe3gjRr5IuxPKSUUFA1g+dIIZeGmxImz3gVMM3H4D2uGP1cOCSitg2j2Wv3hHiXXDrW2i9YdQSe32efPnqIJYhnPNma3N9qGAXkfnXZb1g5le0ewnwh++EaE1VGXGlgdP2Sb4WOgdkrqrZuMhQE3ceQiOY7qPkUD5U6l3CHU1oIfzriwLX1hNeWjggOHFOS21PIqsYWUSJICsnE7LDwQpb49fNaqLeRwb060H5CAVK1jPGQCJiv9+PZ6qTn+vHa1GSm1gikmtVjsO97ep2M01pnvvSlaQeH1rsSpjjejM2mTXry9XP3kUe4Wmg0yEUhBV4igGUE8tEFojw112ot39zZEOLrNhLaVXfGm8rvsZdG9Z1ui1bj+W/V6Axlldk/Pb0f7JCTX3uCPntyAob5KU6S8oyhBDzjWLWxRN7KRFh1AE5O4FbEltuBqZetM2GkYGlCt/yOmXvoZ6doT9LqcYphw==
  template:
    metadata:
      name: my-secret
      namespace: default
    type: Opaque
