---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-secret
  namespace: default
spec:
  encryptedData:
    password: AgCIpVLnzU8GK3Ytoi2bAj2O8+nXu5HMwZ0CJpJYwsb9M29VwX/ZUwkUuykIIU1DN7Hul/ETsSGgLpVg3wTgMZzNvgeyabvJzd2GnjKmHKG31M3SoCRPB9IbJ/6mstH3wuEHyHi1rtqr/anBvzCcc/Ga69cOfrsWV0xQX+Q6ls49anuSbhS/c2V8a0C4An1BMf/36ZJHCFSe6PezfVGvmQ7T87wd3lJIHf2j+blt2cVdD/Z0jpUV6kecEJCRxE/4PKt9+cPgztP4CcdfKoFEcm48ZvJCbR9vs8JM6dXfTMCbOXR4mM3lfdhNP3FeF4K8TsOiYxpt8BaLaJFb+hDSg0u/SXhhMffbL30okyYjXqi4hpywWmTYSOFyMJ1Kwl4Bh8M8kZFTCaAscAy96BMVDG30VMl11JNwG4TZYfVJ8K0VQfg+2WiZq5m6udwL9ZCrgPGYolYxAS4iLYnNrQMziDapjfMwwh+OayU56sZ5i+F0TagNn8WaZC/Yn8zwBdm7qaFatGigiDGeTMIrWFcBR0bUV00Ka+hyFFkFzrfHs1Z4LPRQsmIjMggIGmEm0sB3qKJrTI5qVXibBWa6HBin/jySXzgSuZI6q5AgQ2CEV8mfgwVm4BjoQrM4bWvmHfTsOjyM2Jb6jneHSMztbHfO3xYIiyHHL5IBopJJDcSy4/yerMksVx1MNZiwbYBlYsdnDPj6ytcayTBMD5G716ubLg==
    username: AgBIJr2BHlw61jbUhcssMDRnjETgdX93BymHdQgjTauMZ8X2UO6ewUPmxCUViw/Jx91erxTJF89iCM+7N5DFT508J2uSLW3fjjdf0uwob1PEQD09KtE0B1wDR/HN0fCjdS3efVBZ39lL0fmHpa+9PkIoTnxscaXmJPOKZi1FjMWbT+8ZmEh/zN0Lk4KwG/fKlVFlNDCWcx3taM0pcBlqik6L7kjzYj7MpiOicy65c38ebCZTDbbkEu4dy7iuZsZfMkh8qm8HQhCR3gMgh/sNtXiDol0Xmp3sKEEGRj3EKX1LtbWkBjwVrRb8uqx14LLyJINvYSSIwGzCwRpPgHTzbLsR0BmEW7UzFTo/s3XBaF0zJyBIdqLO00/Rr8Td4W+UPfSu0jw1yAT2zcB1PEzch4F7NG8k74FAgXHUTih4DOB7XuEmNnTP/K2srjJLN2lYdLBPmIkeAIvr7vtaYIxws+Z0p3KcVS3bGtyAEJoPTwJOVLwJ4egLjzPAIoJZbajpdNjmsWPl96Y6OR2P3CJWeonPWSeU7WVIdsYDeEUnNNdlXUvg9P1+VfOAxG44v9o1QGiYATKW2z86wwWPabor6dZA0s9iH8oLRhBihFb0ote+Ti2bUyj9JbDcqcjuSxkotVToNzSWT/15PrlpQZwBSudE4ROlJHOa8Xx1WL2I53CHG9Gm7uQ6oElB5q/eYRPW9fwoLQqqbw==
  template:
    metadata:
      name: my-secret
      namespace: default
    type: Opaque
