---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-secret
  namespace: default
spec:
  encryptedData:
    password: AgBShef1UwAh/DoLZcUvqB00PQ4jIsIluyiyJ9YQgXxF3rsugseKhWmJF2ChpfEP1ddKzJJ8CJOJ/37oWNxqY4uzN32qtxzFyx5cHZmZbBeAXlOB50ONzvUXpkqXzVQtuZaddNDgZKVxwATQaAn2ZQm99ihuyhB4dDkDzxZzShK9loqwHvMrH+tWNMnRQQBfLw2TJxe5t629/jaSP1t+qXClimwX8CZVBOjh+G8xHjTeyjCjVutfdgSxZQrbsCK8IJO/NKZY6LfPa7mdqm5Pt2cwrpK5Sndaus4QNXkuyrWuxbddCZqE6QBEkwjjbWHpZQz+fI9+XxCEKhBtlpTZYTwHj47DW9ii15LDZazVfx9Fit1iMRJxbLM1V/TY1zri5ByWGF8NM35cWMBXThAbGADqdUJfDfa6EO+AJD8R5M7Mo79nxWJdad8be3ZfvQUUjqj73eXy+xxrelUUsVET1g3Snq7ywIRMDvRMTlGNdqIMAdCQvXbi1+R6iOuai/EeoX8AdQ3c7E/TewrcHxeGtW1CUW1EPQWICyB/N9G1FFIW+qAA2YiQLEfw1w59Id4Ig80hHUMNc3FnxCWIijf+bTw4iPdzYCL+Nk0wms+7IgO7WHKcKgxVG41JDd9lJSqHlHJVL1UXSR50/SeuQxP4ghq4rvlYfYX8THSCXpE1nwD3fNkelqcLsqXZhbvw+lvJKTnoDPK8MXOiczhme1ScDA==
    username: AgAHMyEqxU6yu6GwDH4smt28suUv4GNuqeK9MuDzgYVfLCQWSZojvG0s7lXLsoHsoCulSvMJROjV/cy8TfgbFB++/stYyKVPXnRi2HaP4OMgEk+/9BQZyhzvvVREzEGtqr9CX2ZmxUhrAcOB0iN6NFzxTADcqR5xc3uMWQoKH5rSjCSUeuuj6l/ulSEZXEjqJm6e7eJVlSAk1PfEuEbOanzqaZExgOU8Lxt1HW+lQesf0xeFtJV2KBOAcdNcyZgMjWiUzvOGBYZLgQrn8/IgEMWfkDAEc4NRUrH1nJN5TzoHQ30pRlSgfTeJDtMf/ikV/PEyskQ6DJbyPdQ2sr1Hn7y9pdZwsTH9+GvUG2WhwEimIf6b3R8M+NCzONpNTYbJxCXHK41crxaRjh2Re1NiGRuehjE2vWSciYWCjc1Bx9XwsTD0taPB9fGA6uy0b9bZrTSPWPIZu4gY0jMWTPjZUjZQDEr+hmoShL8uPiffjuqcBCLCsHwAQ9YKj44EgnMC/YQwZ3qmURqVgt/d7I6tqWF5oJ94SUUeY8SA91BPlrHeM3PUeZbeAxO2ye8AwJQLyuLAToctyFpSqpfur7A+djyoWqXRCladfRr7fgnSBU0OU1aZIzsI9H+n8tHycXMW28Hmr94RlZJrKHjXv/ODT+EGXDmh+25vjLF65Xc7e4xa1ooG55b4OleEvbJ8mrMpwzvy/KIh3Q==
  template:
    metadata:
      name: my-secret
      namespace: default
    type: Opaque
