---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-secret
  namespace: default
spec:
  encryptedData:
    password: AgAkVI0iN6WfLCFfrCNSFVrGacxx0Th1oOckRE0h68V8aJXfSC8q/rCGAhVkCTSMBh4AFBX2O6NSw0DPDvKZ2NusJKUoRaunn5zJK6lSs+ehpAPcIgnUa6m6nGDSpuvWp1s4OtJgpuO9VnuA2+h4aH5S25Uk9p3Xow4cefpOS6uEU5TqYms3z/1cZfm4/4f4r4/ubJDMcr5NWW1Cu1ZWS/nbEbwQrE729mY9enwFLYI7zNLAft4sMJX7CWL215M7EFk1VPR3pHBhZGzL9afdiA+7JgzFjYazyRRwghsSPCpYwtjo86Ofk19ZiwDAQgLvdCz8Gl3FKCNbChPmmTy3BBLZ+Sr+BZt8voUhlNoVAhfgNADIHm5sLyYmtutW7X0u4yY23xmYEUoheTWAWiLe9i0rYgdqwjx1BVKKjHUsq/UViomzLN4SBmgp1ZA+kOkrs8UVYTrKn9SAt2NVi7APuuIYz7moozErFr1J5lc/QlgflhzAoFl/vRPV+WXidMJYu+khPVKpxtCYrmENNkv6pUTLouI9upVGHZttKXPSZPM7vqOGBuEq63J4xZQtXt1KFwMSe0uKGU3tcryz0bXM/QxFwTP3EB3z5q3jBxxjSqR/l08BAwSm59G8k9waKYDKdgHcUy4jmDMiorbtlBXFA/wfB2Tmlyk/mnm5EbJ8GHOGgbBJi8cmWl2cjqqRZmSy4GUNILU4FhRK3Cj+FNj3fA==
    username: AgCP3POK92zTFnDra/BAxv+ZUSEsIPbhG0WF6PoNrUMXiJYRZoD5CbNxsSgB/ewD8sMb3QcADYh4yh+fRFOEyMqzHqzeLo5uhqH6OzEfs6X8cGUFhw3+hSfhrKYzC09y/oseA9W3vY5yLNUiaYqZGC8IbxJ4AlMM/1EtO32+XWAS9ZV9kBJ0MeHWioav+7zRCjPF9YVi7wzoxOz2nJ/Gbpct43JNZ432OKAZjfsZxmjpJ5BJ3ZQZLmDEcvqkT1jBDcvwhB/nNSrqi6Ef5ktbe/ccXYsCiqfsqQQ6vlcpGgiU69whJssIkBH4vifBZHGgk+O9muNKp7fn6M1HJdUwDNuQCdp4e3vIKccuH4qV2J3HsyC5Zp6VPJ0lvyRaS4qOxBPmmy3n9TbGCp3vpCYAxu5qvreU/Cdj1Dewwu3eEuRWpTNC6D77+nbomz+JZCFet2rBjAeXuQ0vwB7ZSpkv71JetwFmysbbkqhAmTik7Uoyn/tSIPOCEJj8WnsKfQNeZZGkUOUKDgo2NahQ2ms0qM8uw+Mr9khmwBW37FSwuIdDvBt0io44+wPwUSExTVXsbj09sVHlMCcekKI16NHGY5LJx0qosIV67rynEj+GzLsQwa3328L6Gkse+RV8okfz+e93b0+bk3vZQ8xb74xOnnvJbsE480JJ2u3wUP0SRbICQzeFRYLyrqP1+AUrkxGIVmVe2DL64w==
  template:
    metadata:
      name: my-secret
      namespace: default
    type: Opaque
