---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-secret
  namespace: default
spec:
  encryptedData:
    password: AgAe4+6OsvsPuMaM23A/rXw7hFlcezZoEwvLo29+5DTDY54FJiP8BW8AxGgW270ODExMa1YINVTUdt6i7J6rW0LgXIZyZ9qqdHhvG/bP3X7TcWVDZHTIiH+71qggwZ/SoV4AUoi1QaUU8WtgZvNEMjZNCdWo9RB4lg5HqAAuwI02QX2Py07yUmtOzN5DNG0Hd5vB+1Nq0OzhKm+08kVlPsrHRrftePm//6l+jHEaYZJXciTyIz6NEvOzrh0YXJ73z0Sj8tvCV+AcpNk9K2NZjSLFOeJCtGcx/ukzf28MhaOmuAkPECX6H0eA0U2L7gc0in8BYdKb6M0AG4gb0P1ttbLyyVi/triHEiEhoNw0hxlhb1duJ96ELqPzxjORIwlaJDEAIDxQ9lT2HzJcZxkq+NslcDHO2oeG0cDBSbAjIg0BCQOWpcyznYqs3A1pMfZLRuWrNexTLi1ChKKb5F6nAzkNMIk5RB9e1g7RUA3++V4SHK4VOU9sOfNKtuxp0bo8ZwmeNJOpJgnWGksLIxrOFX/e/eEh72cObCfZrESaaCR+MRKthS6G/6nCWOgLcLUgAdfoBtA7O2WzYT1SbSOPQ2oGG5YeIaPxidemTYhpvcXlo/BO9BQQy2j3wXchcsWBXVB7yWYCRsYssjq/mJhiXb3/JwXvuuwGF177MJrOHF0V9B1ue9CQNqsXi7wOTqbEHcOZGilmUrq56yrpWlJQcw==
    username: AgB6pXPKsPXcxroP2fFrOWtTciXK6iJy+6sUA7Z/9bIEfxIY1iHSyuhruK8+0YzYSbtiVQ96k8CTBF2AJBt2ScgZHvEAQMg+DQ8aJ+Amd91u3dsOMnU8EjzlC8SUcTIMZW2jHqaT9rCuwRR9Nvd19AXwkOOrPzBYv6ZDNPCukr4nmTAxB3aFj5vIo3pEB0AcQ9jQrHGubSoOyjHqNN6AXTIEcdbGyYReMsN2KXVRRKMH4fcjNU8Y5ooMOwzKmTrg0VFSuZ2ZKrzpiIJ9h/T7/QoF9+xMOOY4f5qsLE+/l+8J4TDKn9fvK+8qfHN/dovkY89ajWDBRPjsww6GhHaPbVTWlhzaSAj8OAtcgDfCpjFf0sjnl4afNvyiDV3QSrPG5XW69+iQYwsmjtV7DR/NSA73+5PuE2nuo+g/nLXuC53D1KnEmyLeTAcMoJmYW3L2undnhWtJINvnShHcdKrTTWpLQSoqW4qT6gRsjFJHr57C1c7I/JXJNjWJHOEtB+QjJu4SJ1Rw39yHx2H50vgR2SlobgxengBqjRXNAnLBknCrYZD2KFoqH8+EHfqQDeHID7KelaSMhvydqodSp87XopC9iyFLQXvkenS7T/ajovue6Z7KrbXHxOSW3p0Mco350I/+YAizIucoo9+5UNZnrbVAtdYskGlg1FbkqUpxL7HW3wjXJa2TaL1dYWUFPQhIxdGZc9l4uw==
  template:
    metadata:
      name: my-secret
      namespace: default
    type: Opaque
